- hosts: all
  tasks:
    - debug:
        msg: "This is the verify-test-success/run.yaml task"
    - debug:
        msg: "This is the test_command: {{ test_command }}"
    - name: Run test command
      command: "touch run-file-flag"
