- name: Set zuul-log-path fact
  include_role:
    name: set-zuul-log-path-fact

- name: Return log URL to Zuul
  delegate_to: localhost
  zuul_return:
    data:
      zuul:
        log_url: "{{ zuul_log_url }}/{{ zuul_log_path }}/"
  when: zuul_log_url is defined
