- name: Set log path for a change
  when: zuul.change is defined
  set_fact:
    zuul_log_path: "{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.job }}"

- name: Set log path for a ref update
  when: zuul.newrev is defined
  set_fact:
    zuul_log_path: "{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.job }}"

- name: Set log path for a periodic job
  when: zuul.change is not defined and zuul.newrev is not defined
  set_fact:
    zuul_log_path: "{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.job }}"
